import Config

config :pot_examples, Postgres.Repo,
  port: 7432,
  stacktrace: true,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "pot_examples_dev",
  ownership_timeout: 300_000,
  #  disable_composite_types: true,
  pool_size: System.schedulers_online() * 2

config :pot_examples, Cubes.Repo,
  port: 15432,
  stacktrace: true,
  username: "username",
  password: "password",
  hostname: "localhost",
  database: "test",
  ownership_timeout: 300_000,
  #  disable_composite_types: true,
  pool_size: 1


# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pot_examples, ExamplesOfPoTWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "eTqCPf3S7cYnb45LMek78Va2Xe9BP7uwYY3bAnoOcNyRat+/8boiJ40Wanq+fyjK",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pot_examples, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pot_examples, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :pot_examples, ExamplesOfPoTWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/pot_examples_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pot_examples, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
